# Generated by Django 2.0.5 on 2018-09-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_order', 'Can order the drink'), ('can_server', 'Can prepare and serve the drink')),
            },
        ),
    ]
