# Generated by Django 2.0.5 on 2018-09-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodinstance',
            options={'permissions': (('can_order', 'Can order the drink'), ('can_serve', 'Can prepare and serve the drink'))},
        ),
    ]
