# Generated by Django 2.0.5 on 2018-09-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20180909_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodInstance',
        ),
    ]
