# Generated by Django 2.0.5 on 2018-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0004_delete_foodinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_order', 'Can order the drinks'), ('can_serve', 'Can prepare and serve the drinks')),
            },
        ),
    ]
