# Generated by Django 2.0.5 on 2018-09-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_orderinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_open', models.BooleanField()),
            ],
        ),
    ]
