# Generated by Django 2.0.5 on 2018-09-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_businessinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessInstance',
        ),
    ]
