# Generated by Django 2.0.5 on 2018-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_delete_businessinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_status', models.CharField(max_length=10)),
            ],
        ),
    ]
