# Generated by Django 2.0.5 on 2018-10-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_businessobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinstance',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
